import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useEffect, useState, SyntheticEvent } from 'react';
import * as io from "socket.io-client";
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [socket, setSocket] = useState<any>();
  const [message, setMessage] = useState<string>("");
  const [receivedMessages, setReceivedMessages] = useState<string[]>([]);

  useEffect(() => {
    const SOCKET_HOST: string = process.env.NEXT_PUBLIC_SOCKET_SERVER || "";
    const clientSocket = io.connect(SOCKET_HOST, {
      transports: ["websocket"]
    });

    setSocket(clientSocket);
  }, []);

  useEffect(() => {
    if (!socket) return;

    socket.on("receive_message", (data: any) => {
      setReceivedMessages((prevMessages: string[]) => [
        ...prevMessages,
        data.message
      ]);
    });
  }, [socket]);

  const sendMessage = (event: SyntheticEvent) => {
    event.preventDefault();
    
    socket.emit("send_message", {
      message
    });

    setMessage("");
  }

  return (
    <div>
      <Head>
        <title>CoTalk - Let&apos;s talk with your coworker!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={ styles.main }>
        
        <div className={ styles.chatbox }>
          <form onSubmit={sendMessage}>
            <input
              type="text"
              placeholder='Message...'
              value={ message }
              onChange={(event) => {
                setMessage(event.target.value);
              }}
            />
            <button type="submit">Send Message</button>
          </form>
        </div>

        <div className={ styles.messages }>
          {receivedMessages.map((msg: string) => (
            <div key={ msg }>{ msg }</div>
          ))}
        </div>

      </main>

      <footer>
        
      </footer>
    </div>
  )
}

export default Home
